name: Build iOS IPA for TrollStore

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build IPA for TrollStore
        run: |
          bash build_trollstore_ipa.sh
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiuBonVSub-TrollStore
          path: dist/MiuBonVietsub-TrollStore.ipa
